services:
  - type: web
    name: chatbot-app
    env: docker
    dockerfilePath: ./Dockerfile
    plan: free
    numInstances: 1
    healthCheckPath: /
    envVars:
      - key: FLASK_ENV
        value: production
      - key: OPENAI_API_KEY
        sync: false
      - key: POSTGRES_USER
        fromService:
          type: pserv
          name: chatbot-db
          property: user
      - key: POSTGRES_PASSWORD
        fromService:
          type: pserv
          name: chatbot-db
          property: password
      - key: POSTGRES_DB
        fromService:
          type: pserv
          name: chatbot-db
          property: database
      - key: POSTGRES_HOST
        fromService:
          type: pserv
          name: chatbot-db
          property: host
      - key: REDIS_URL
        fromService:
          type: redis
          name: chatbot-redis
          property: connectionString
    disk:
      name: uploads
      mountPath: /app/uploads
      sizeGB: 1
    autoDeploy: true

  - type: pserv
    name: chatbot-db
    env: docker
    plan: free
    dockerCommand: postgres
    disk:
      name: pg-data
      mountPath: /var/lib/postgresql/data
      sizeGB: 1
    envVars:
      - key: POSTGRES_USER
        value: postgres
      - key: POSTGRES_PASSWORD
        generateValue: true
      - key: POSTGRES_DB
        value: chatbot_db
    autoDeploy: false

  - type: redis
    name: chatbot-redis
    ipAllowList: []
    plan: free
    maxmemoryPolicy: volatile-lru